# Generated by Django 4.2.7 on 2023-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0003_remove_order_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.BigIntegerField(null=True),
        ),
    ]
