# Generated by Django 4.2.7 on 2023-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0005_rename_price_orderitem_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
