# Generated by Django 4.2.7 on 2023-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0007_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
