# Generated by Django 4.2.7 on 2023-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
