# Generated by Django 4.2.7 on 2023-12-22 06:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0011_alter_order_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=1, editable=False, populate_from="first_name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="adf", editable=False, populate_from="order", unique=True
            ),
            preserve_default=False,
        ),
    ]
