# Generated by Django 4.2.7 on 2023-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0014_alter_orderitem_shipping_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_choice",
            field=models.CharField(
                choices=[
                    ("free", "free Shipping"),
                    ("local ", "Local Pickup from store"),
                    ("express", "Express Shipping"),
                    ("standard", "Standard Shipping"),
                    ("same_day", "Same day shipping"),
                ],
                default="free",
                max_length=10,
                null=True,
            ),
        ),
    ]
