# Generated by Django 4.2.7 on 2023-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0016_shipping_remove_orderitem_shipping_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
