# Generated by Django 4.2.7 on 2023-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0018_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total",
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash_on_delivery", "Cash on Delivery"),
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
