# Generated by Django 4.2.7 on 2023-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0019_orderitem_total_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="total",
            field=models.BigIntegerField(null=True),
        ),
    ]
