# Generated by Django 4.2.7 on 2023-12-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0020_alter_orderitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="total",
            field=models.CharField(null=True),
        ),
    ]
