# Generated by Django 4.2.7 on 2023-12-25 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0024_tax_orderitem_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="tax_rate",
        ),
    ]
