# Generated by Django 4.2.7 on 2024-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0026_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="wallet_name",
        ),
        migrations.AddField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(default=2, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
