# Generated by Django 4.2.7 on 2024-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0027_remove_wallet_wallet_name_wallet_wallet_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
