# Generated by Django 4.2.7 on 2024-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0028_remove_order_is_deleted_orderitem_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=models.CharField(blank=True, null=True),
        ),
    ]
