# Generated by Django 4.2.7 on 2024-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0029_alter_order_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default=1, max_length=260),
            preserve_default=False,
        ),
    ]
