# Generated by Django 4.2.7 on 2024-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0030_order_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="order",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
