# Generated by Django 4.2.7 on 2024-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0031_remove_orderitem_is_deleted_order_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tax",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
