# Generated by Django 4.2.7 on 2024-01-07 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0033_alter_coupon_discount_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="is_deleted",
        ),
    ]
