# Generated by Django 4.2.7 on 2024-01-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userorder", "0034_remove_coupon_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="shipping_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
                ("country", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
