# Generated by Django 4.2.7 on 2024-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0036_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping_address",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shipping_address",
            name="second_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shipping_address",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
