# Generated by Django 4.2.7 on 2024-01-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0037_shipping_address_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping_address",
            name="first_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shipping_address",
            name="second_name",
            field=models.CharField(default="afda", max_length=100),
            preserve_default=False,
        ),
    ]
