# Generated by Django 4.2.7 on 2024-01-10 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0038_alter_shipping_address_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
    ]
