# Generated by Django 4.2.7 on 2024-01-10 19:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0040_alter_order_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="user.first_name", unique=True
            ),
        ),
    ]
