# Generated by Django 4.2.7 on 2024-01-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminhome", "0014_products_tax_rate"),
        ("userorder", "0042_order_first_name_alter_order_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminhome.category",
                    ),
                ),
            ],
        ),
    ]
