# Generated by Django 4.2.7 on 2024-01-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminhome", "0014_products_tax_rate"),
        ("userorder", "0043_categoryoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryoffer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryoffer",
                to="adminhome.category",
            ),
        ),
    ]
