# Generated by Django 4.2.7 on 2023-11-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
