# Generated by Django 4.2.7 on 2023-11-28 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usermain", "0002_alter_users_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
    ]
