# Generated by Django 4.2.7 on 2023-12-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0002_auto_20190420_0723'),
        ('usermain', '0006_rename_customer_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTOTPDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
