# Generated by Django 4.2.7 on 2023-12-08 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usermain", "0007_customtotpdevice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomTOTPDevice",
        ),
    ]
