# Generated by Django 4.2.7 on 2023-12-01 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminhome", "0002_remove_products_product_image_brand_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
