# Generated by Django 4.2.7 on 2023-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_remove_brand_slug_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
