# Generated by Django 4.2.7 on 2023-12-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminhome", "0011_brand_is_deleted_category_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand_name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="Category_name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
