# Generated by Django 4.2.7 on 2023-12-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userorder", "0025_remove_orderitem_tax_rate"),
        ("adminhome", "0013_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userorder.tax",
            ),
        ),
    ]
